#!/bin/bash
count=`cat /upd_repo/li_updates/pkgdownload.list | wc -l`
ctr=0
echo "###############################################"
echo "# Updating local repo from package list       #"
echo "# each package dependences will be downloaded #"
echo "###############################################"
echo ""

while IFS='' read -r line || [[ -n "$line" ]]; do
    ctr=$((ctr + 1))
    echo "Checking ($ctr / $count): $line"
    repotrack -q -a x86_64 -p /upd_repo/li_updates/primary/ $line
done < /upd_repo/li_updates/pkgdownload.list 
rm -rf /upd_repo/li_updates/primary/repodata
createrepo /upd_repo/li_updates/primary/
tar -cvzf /upd_repo/li_updates/primary/rpm-gpg-keys.tgz /etc/pki/rpm-gpg/*
reboot
